services:
  web:
    build: .
    ports:
      - "8000:5000"
  redis:
    image: "redis:alpine" 
  
  postgres:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    ports:
      - "5432:5432"