services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: ankane/pgvector:latest
    hostname: "postgres"
    networks:
      - overlay
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "8080:80"
    networks:
      - overlay
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin:

networks:
  overlay: